services:
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_BACKEND_URL: "http://localhost:3010"
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "3010:3010"
    environment:
      LOGGER_URL: http://host.docker.internal:3020
      GENAI_API_KEY: ${GENAI_API_KEY}
  logger:
    build: ./logger
    ports:
      - "3020:3020"
      